<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-35ULCHUU" failures="7" tests="46" name="com.runner.Runner" time="191.191" errors="1" timestamp="2023-01-06T13:04:07 EST" skipped="0">
  <testcase classname="com.runner.Runner" name="runScenario" time="5.675">
    <failure message="expected [please enter valid password format] but found [password_mismatch:The two password fields didn’t match.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [please enter valid password format] but found [password_mismatch:The two password fields didn’t match.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.stepDefinations.RegisterStepDef.user_should_get_enter_valid_input_error_message(RegisterStepDef.java:163)
at ✽.user should get enter valid input error message "please enter valid password format"(file:///C:/Users/vanis/eclipse-numpyninja/DS-ALGO/src/test/resources/features/2register.feature:89)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="5.543">
    <error message="stale element reference: element is not attached to the page document
  (Session info: chrome=108.0.5359.125)
For documentation on this error, please visit: https://selenium.dev/exceptions/#stale_element_reference
Build info: version: &#039;4.7.1&#039;, revision: &#039;c6795baf1a3&#039;
System info: os.name: &#039;Windows 11&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;17.0.5&#039;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [08293bf1de498b007c4b9392ea2a8b05, getElementText {id=791f1cde-bb6c-403d-b7eb-c4fdef77810a}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 108.0.5359.125, chrome: {chromedriverVersion: 108.0.5359.71 (1e0e3868ee06..., userDataDir: C:\Users\vanis\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:49421}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:49421/devtoo..., se:cdpVersion: 108.0.5359.125, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on WINDOWS (08293bf1de498b007c4b9392ea2a8b05)] -&gt; id: id_username]
Session ID: 08293bf1de498b007c4b9392ea2a8b05" type="org.openqa.selenium.StaleElementReferenceException">
      <![CDATA[org.openqa.selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document
  (Session info: chrome=108.0.5359.125)
For documentation on this error, please visit: https://selenium.dev/exceptions/#stale_element_reference
Build info: version: '4.7.1', revision: 'c6795baf1a3'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.5'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [08293bf1de498b007c4b9392ea2a8b05, getElementText {id=791f1cde-bb6c-403d-b7eb-c4fdef77810a}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 108.0.5359.125, chrome: {chromedriverVersion: 108.0.5359.71 (1e0e3868ee06..., userDataDir: C:\Users\vanis\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:49421}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:49421/devtoo..., se:cdpVersion: 108.0.5359.125, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on WINDOWS (08293bf1de498b007c4b9392ea2a8b05)] -> id: id_username]
Session ID: 08293bf1de498b007c4b9392ea2a8b05
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:551)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:257)
at org.openqa.selenium.remote.RemoteWebElement.getText(RemoteWebElement.java:207)
at jdk.internal.reflect.GeneratedMethodAccessor101.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:52)
at jdk.proxy2/jdk.proxy2.$Proxy44.getText(Unknown Source)
at com.pageObjects.RegisterPage.validatecompare(RegisterPage.java:153)
at com.stepDefinations.RegisterStepDef.user_should_get_password_not_similar_to_username_error_message(RegisterStepDef.java:175)
at ✽.user should get password not similar to username error message "password can not be similar as username"(file:///C:/Users/vanis/eclipse-numpyninja/DS-ALGO/src/test/resources/features/2register.feature:98)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="4.602"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="4.589"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="12.575"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="2.937"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.008"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="1.017"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="1.106"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="4.368"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="2.814"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.382"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="4.898"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="4.281"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="4.053">
    <failure message="Result do not match expected [submission success] but found [ Some Tests failed. Please review code]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Result do not match expected [submission success] but found [ Some Tests failed. Please review code]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at com.stepDefinations.ArraysStepDef.the_user_should_be_presented_with_successful_submission_message(ArraysStepDef.java:160)
at ✽.The user should be presented with successful submission message(file:///C:/Users/vanis/eclipse-numpyninja/DS-ALGO/src/test/resources/features/5arrays.feature:110)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.313"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="8.131"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="0.888"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="5.265"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="1.914"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="2.168"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="5.736">
    <failure message="expected [password should contain atleast eight characters.] but found [password_mismatch:The two password fields didn’t match.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [password should contain atleast eight characters.] but found [password_mismatch:The two password fields didn’t match.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.stepDefinations.RegisterStepDef.user_should_get_password_atleast_eight_char_error_message(RegisterStepDef.java:149)
at ✽.user should get password atleast eight char error message "password should contain atleast eight characters."(file:///C:/Users/vanis/eclipse-numpyninja/DS-ALGO/src/test/resources/features/2register.feature:81)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.409"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="1.297">
    <failure message="Result do not match expected [NameError: name &#039;hello&#039; is not defined on line 1] but found [NameError: name &#039;hellosortedSquares&#039; is not defined on line 9]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Result do not match expected [NameError: name 'hello' is not defined on line 1] but found [NameError: name 'hellosortedSquares' is not defined on line 9]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at com.stepDefinations.ArraysStepDef.the_user_should_be_presented_with_error_message_as(ArraysStepDef.java:187)
at ✽.The user should be presented with error message as "NameError: name 'hello' is not defined on line 1"(file:///C:/Users/vanis/eclipse-numpyninja/DS-ALGO/src/test/resources/features/5arrays.feature:180)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="2.091"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="4.829">
    <failure message="Result do not match expected [submission success] but found [ Some Tests failed. Please review code]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Result do not match expected [submission success] but found [ Some Tests failed. Please review code]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at com.stepDefinations.ArraysStepDef.the_user_should_be_presented_with_successful_submission_message(ArraysStepDef.java:160)
at ✽.The user should be presented with successful submission message(file:///C:/Users/vanis/eclipse-numpyninja/DS-ALGO/src/test/resources/features/5arrays.feature:130)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="4.457"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.779"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="2.786"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="2.919"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="0.916"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="2.793"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="4.871"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="4.396"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.586"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="4.959">
    <failure message="Result do not match expected [submission success] but found [Error occurred during submission]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Result do not match expected [submission success] but found [Error occurred during submission]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at com.stepDefinations.ArraysStepDef.the_user_should_be_presented_with_successful_submission_message(ArraysStepDef.java:160)
at ✽.The user should be presented with successful submission message(file:///C:/Users/vanis/eclipse-numpyninja/DS-ALGO/src/test/resources/features/5arrays.feature:150)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.833"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="8.176"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="5.991"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="5.788"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.138"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="11.322"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.297"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="2.910"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="2.899"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="4.486">
    <failure message="Result do not match expected [submission success] but found [ No tests were collected]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Result do not match expected [submission success] but found [ No tests were collected]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at com.stepDefinations.ArraysStepDef.the_user_should_be_presented_with_successful_submission_message(ArraysStepDef.java:160)
at ✽.The user should be presented with successful submission message(file:///C:/Users/vanis/eclipse-numpyninja/DS-ALGO/src/test/resources/features/5arrays.feature:170)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- com.runner.Runner -->
